import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import NavBar from "../components/NavBar";
import Results from "../components/Results";

export default function Home() {
  return (
    <div>
      <Head>
        <title>hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* header component */}
      <Header></Header>
      {/*navbar component */}
      <NavBar></NavBar>
      {/*dashboard component*/}
      <Results></Results>
    </div>
  );
}
